### ISSUE TITLE
Task error reporting

### ISSUE THREAD

**Issue by jdeniau** [romanschejbal/gassetic#12]
``` yaml
requires:
     freez: gulp-freeze
# ...

    tasks: 
        - freeze
```

The "freeze" ('e' is missing) task is not defined, but the console does not explain it, the `gassetic` command only exits
