### ISSUE TITLE
Symfony2 integration not working

### ISSUE THREAD

**Issue by telemetrik** [romanschejbal/gassetic#16]
I've created a very simple `gassetic.yml` (based on your Symfony docs):

```
requires:
    concat: gulp-concat
    uglify: gulp-uglify
    freeze: gulp-freeze
    minify: gulp-minify-css

mimetypes:
    css:
        dev:
            outputFolder: web/dist/css
            webPath: /compiled/css
            tasks: []
        files:
            foo.css:
                - src/Acme/DemoBundle/Resources/public/css/demo.css

default:
    - css
```

Please not that there is no `replacementPaths` since the example didn't provide one.
I know that's why my `<!-- dev:foo.css --><!-- endbuild -->` in `/symfony/src/Acme/DemoBundle/Resources/views/layout.html.twig` aren't replaced. However where should `replacementPahts` point? To `src/**/*Bundle/Resources/view` and keep them under VCS and swear to god everyone will grunt `gassetic` before push? That sounds really excessive. I'm guessing that pointing them to `app/cache` won't work as well since we're dealing with PHP compiled templates there. How did you manage to make it work?
