### ISSUE TITLE
Splitting assets

### ISSUE THREAD

**Issue by amqex** [romanschejbal/gassetic#24]
There seems to be an issue with splitting assets. I have included two example scenarios below:

Sample **gassetic.yml**

```
requires:
    sass: gulp-ruby-sass
mimetypes:
    css:
        dev:
            outputFolder: web/tmp/css
            webPath: /tmp/css
            tasks:
                - { name: sass, args: { style: 'expanded' } }
        prod:
            outputFolder: web/compiled/css
            webPath: /compiled/css
            tasks:
                - { name: sass, args: { style: 'compressed' } }
        files:
            main.css:
                - assets/scss/file1.scss
            global.css:
                - assets/scss/file2.scss
replacementsPaths:
    - app/**/*.html.twig
    - src/**/*.html.twig
default:
    - css
```

**Scenario 1**
Including css for file name main.css

```
{% if app.environment == 'prod' %}
  <!-- prod:main.css --><!-- endbuild -->
{% else %}
  <!-- dev:main.css --><!-- endbuild -->
{% endif %}
```

Even though I only included main.css, it also includes the css from global.css file name and it becomes:

```
<!-- dev:main.css -->
<link rel="stylesheet" href="/tmp/css/main.css/file1_0.css">
<link rel="stylesheet" href="/tmp/css/main.css/file2_0.css">
<!-- endbuild -->
```

**Scenario 2**
Including css for both main.css and global.css file names

```
{% if app.environment == 'prod' %}
  <!-- prod:main.css --><!-- endbuild -->
  <!-- prod:global.css --><!-- endbuild -->
{% else %}
  <!-- dev:main.css --><!-- endbuild -->
  <!-- dev:global.css --><!-- endbuild -->
{% endif %}
```

Each filename includes css from both files

```
<!-- dev:main.css -->
<link rel="stylesheet" href="/tmp/css/main.css/file1_0.css">
<link rel="stylesheet" href="/tmp/css/main.css/file2_0.css">
<!-- endbuild -->

<!-- dev:global.css -->
<link rel="stylesheet" href="/tmp/css/global.css/file1_0.css">
<link rel="stylesheet" href="/tmp/css/global.css/file2_0.css">
<!-- endbuild -->
```
