### ISSUE TITLE
Removing filename from the script path

### ISSUE THREAD

**Issue by goosechaser** [romanschejbal/gassetic#27]
Assume that this is my `yml` config:

```
[...]
        prod:
            outputFolder: dist
            webPath:      /dist
            tasks: [] 
        files:
            javascripts.js:
                - vendor/js/js1.js
                - vendor/js/js2.js
[...]
```

The generated HTML will contain the following:

```
<!-- prod:dev -->
<script src="/dist/javascripts.js/js1.js"></script>
<script src="/dist/javascripts.js/js2.js"></script>
<!-- endbuild -->
```

Since I am not running any tasks, the script `src` should be `/dist/` + `js1.js` and `js2.js`. If I were running a concat, then the script `src` should become `/dist/javascripts.js`. 

Basically, it makes no sense to include the filename from YML into the full path.
