### ISSUE TITLE
Why extra folder?

### ISSUE THREAD

**Issue by andrewtch** [romanschejbal/gassetic#44]
```yml
files:
    style.css:
        - html/src/styles/main.less
```

why gassetic is creating ```%outputfilder%/style.css/style.css```, and not just plain ```%outputfolder%/style.css``` ?
