### ISSUE TITLE
Can i use external config?

### ISSUE THREAD

**Issue by muhibbudins** [romanschejbal/gassetic#72]
Hello there,

I few some trouble when i'm make config with many file, can i import config list of file to use in gassetic.yml?

Like symfony have ..
```yml
# app/config/config.yml
imports:
    - { resource: '%kernel.root_dir%/parameters.yml' }
```

Maybe like this
```yml
...
                # This is a cache busting gulp plugin that appends
                #  an md5 of the contents to the filename
                - { name: freeze }
            htmlTag: '<link rel="stylesheet" type="text/css" href="{{ asset("%path%") }}">' # custom html tag

        # This is the list of source files to apply the above settings
        files:
            backend.css: # This is the output filename
                imports:
                    - SomeFile.yml # Another config file
...
```
