### ISSUE TITLE
Livereload browser not working (?)

### ISSUE THREAD

**Issue by maxperei** [romanschejbal/gassetic#79]
hi there, it seems that everything is working except gulp-livereload, here is `gassetic.yml` :
```
requires:
    sass: gulp-sass
    clean: gulp-clean-css
    concat: gulp-concat
    uglify: gulp-uglify
    livereload: gulp-livereload
mimetypes:
    # This section contains the formatters for the css files
    css:
        dev:
            outputFolder: web/tmp/css
            webPath:      /tmp/css
            tasks:
                - { name: sass }
                - { name: livereload, args: { start: true } }
        prod:
            outputFolder: web/compiled/css  # The output folder for your saving your compiled files
            webPath:      /compiled/css     # The web path for the compiled files
            # Run these tasks on your compiled files
            tasks:
                - { name: sass }
                - { name: clean }
                - { name: concat, args: '%filename%' }
            htmlTag: '<link rel="stylesheet" type="text/css" href="{{ asset("%path%") }}">' # custom html tag

        # This is the list of source files to apply the above settings
        files:
            main.css: # This is the output filename
                - bower_components/bootstrap/dist/css/bootstrap.css
                - sass/responsive.scss
                - sass/frontend.scss
                - sass/dashboard.scss

        # Watch these files for changes (optional)
        watch:
            - sass/**/*.scss

    # This section contains the formatters for your JS files
    js:
        dev:
            outputFolder: web/tmp/js
            webPath:      /tmp/js
            tasks: []
        prod:
            outputFolder: web/compiled/js  # Save the files here
            webPath:      /compiled/js     # Specify the web path
            tasks:
                - { name: concat, args: '%filename%' }
                - { name: uglify, args: { mangle: false } }

        # Here is a list of files to apply the above tasks to
        files:
            main.js: # This is the output filename
                - bower_components/jquery/dist/jquery.js
                - bower_components/bootstrap/dist/js/bootstrap.js

# This is the list of files/paths to search and find the replacement tags to insert the
# generated <script> or stylesheet tags
replacementPaths:
    - src/**/*.html.twig
    - app/**/*.html.twig

default:
    - js
    - css
```
thanks y'all
