### ISSUE TITLE
Recursive copy

### ISSUE THREAD

**Issue by KhanMaytok** [romanschejbal/gassetic#80]
I tried to copy a folder with

```
fonts:
    dev:
      outputFolder: web/tmp
      tasks: []
      autoRenaming: false
    prod:
      outputFolder: web/compiled
      tasks: []
    files:
      fonts:
        - app/Resources/assets/fonts/*
```

But it dont copy the folder recursively. Any help? I tried with folder/**/*.* But don't works
